### ISSUE TITLE
Feature Request: http redirect

### ISSUE THREAD

**Issue by knight42** [mosn/mosn#1255]
### The New Feature

Currently MOSN is lack of the support of http redirect, which makes user unable to perform redirect in [`VirtualService`](https://istio.io/latest/docs/reference/config/networking/virtual-service/#HTTPRedirect).

It is worth noting that envoy has this feature https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-msg-config-route-v3-redirectaction, and I noticed that related code was commented out in MOSN: https://github.com/mosn/mosn/blob/0da49757f0cc75955813f3372d3ff5ce4ce1cf7c/pkg/xds/conv/convertxds.go#L1063-L1074

~~Is it intended that MOSN will not have this feature or is it just not implemented yet?~~

### Roadmap

* [ ] add `RedirectResponseRule` interface to `mosn.io/api` https://github.com/mosn/api/pull/10
* [ ] add `RedirectAction` struct to `mosn/pkg/config/v2` and implement `RedirectResponseRule` interface in `mosn/pkg/router`
* [ ] convert `xdsroute.RedirectAction` to redirect action that mosn is able to recognize

**Comment by knight42** [comment]
If this is a desired feature, I would like to implement it.

**Comment by knight42** [comment]
cc @taoyuanyuan @nejisama what do you think? really looking forward to your comments!

**Comment by wangfakang** [comment]
@knight42  yeah, It's a general feature, and you are welcome to contribute PR. 
thx

**Comment by knight42** [comment]
/assign 

@wangfakang I have implemented this feature locally and will file PRs asap.
